{% set version = "0.26.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-parameters
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/parameters_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/parameters/parameters_{{ version }}.tar.gz
  sha256: 6f0a412d25872d69a7f3ecac7bde67dd38f8be6c5cb9101fc914b505c49c1804

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bayestestr >=0.15.2
    - r-datawizard >=1.0.2
    - r-insight >=1.2.0
  run:
    - r-base
    - r-bayestestr >=0.15.2
    - r-datawizard >=1.0.2
    - r-insight >=1.2.0

test:
  commands:
    - $R -e "library('parameters')"           # [not win]
    - "\"%R%\" -e \"library('parameters')\""  # [win]

about:
  home: https://easystats.github.io/parameters/
  dev_url: https://github.com/easystats/parameters/
  doc_url: https://easystats.github.io/parameters/reference/
  license: GPL-3.0-only
  summary: Utilities for processing the parameters of various statistical models. Beyond computing p values, CIs, and other indices for a wide variety of models (see support list of insight; Lüdecke, Waggoner & Makowski (2019) <doi:10.21105/joss.01412>), this package implements features like standardization or bootstrapping
    of parameters and models, feature reduction (feature extraction and variable selection) as well as conversion between indices of effect size.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
