travis:
  secure:
    BINSTAR_TOKEN: cn9lP5gYQj3nap7cjxV08fmLTfxZybfq0Y/iWfGQRcEB7ITeoRFF4GkULUrokt1sHJFHz7UJhSLs8whZvrCyk9DZC4+vc8UvYd3FnkXyZsU1wXYpMUlSMEHcuVJ6TvL5z3naiARbjzq6X9tCxZaQ43IYmiNN2AoGdNJ99+iHjLJ6+sIeK9Sk1bd1X0Aolc8BcrWshGnMrqg2aCUQwJcOu/HT5IJVftgpqG3yxhQwHj2+SmMOJwxPVJBErN/MU/jsKxKN8LoJBcx+iwrVWIQp36bIzPoG4BIe7qjOIpFyEmPLIH38uxUyYF4PmZ2pUTgZbgwevnhMMp02V2Xj6bBDLgUICdZpgPBtdMxiKgq10yd8YnXXbF7/mSobixVquBGaSLGD7ciurpFe1jmAV00f0c62SCP9Q63N94G+TzDbJmqdUTyna6IuF0LRbJiq1sLvGc3LdVYf5eq8Tz23TJyYC5+bKJmzSmZ+8swA2C+geEeoP8Bj+bOjZzMR8OToU7MmNEFn0f0yTqC+zIdjVKJgqdwv79O2Ufjr9O8Z+HyRHyQ+zlVHBZpyrhuChOd6kKWDf/2who/hnuSfsCAtJq0Y6vretXKQjqc2ba4cFNfZZjSoZRs4E9zShuf62LPk2fgFRUqU7XnyIknBjsMMuRYTXd4bE7bOGx93CW6G2wznWjE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
